### ISSUE TITLE
Get token information from Groq.

### ISSUE THREAD

**Issue by fadingNA** [Mounayer/OptimizeIt#12]
Based on the Groq instances, it would be a good idea to provide users with an option `--token_usage` or `-t` to monitor how many tokens are being returned or used for optimization purposes. This is important because some blocks of code might exceed the token limit applied to each model.

**Comment by Mounayer** [comment]
That's a great idea @fadingNA! Although I think `--token-usage` follows the convention of long commands for CLI tools more closely than `--token_usage`!

**Comment by fadingNA** [comment]
got it I will use --token-usage instead of _ , and the arcronym will be -tu @Mounayer  or do oyu have any preferable in mind?

**Comment by Mounayer** [comment]
I agree with you that `-tu` fits perfectly!

**Comment by fadingNA** [comment]
@Mounayer  Could you give me permission to push to different branch please 

<img width="885" alt="Screenshot 2024-09-15 at 2 11 12 PM" src="https://github.com/user-attachments/assets/ccddd872-4fe3-43d6-bd14-8b7fceffe53d">


Thanks Mounayer

**Comment by Mounayer** [comment]
That's weird -- did you fork my repo and you're working on a branch? Because I looked at your forked repo and it doesn't show any branches. Maybe you're trying to push directly into `my` repo

**Comment by fadingNA** [comment]
@Mounayer I have made a PR https://github.com/Mounayer/OptimizeIt/pull/13

Thanks

**Comment by Mounayer** [comment]
Closed with PR #13
