### ISSUE TITLE
Nitpick: Project repository description

### ISSUE THREAD

**Issue by cleobnvntra** [Mounayer/OptimizeIt#5]
# Description
A short description for the project repository is not provided.

![image](https://github.com/user-attachments/assets/68a89dd0-3292-4d37-ad08-42ba54691f44)

![image](https://github.com/user-attachments/assets/84ffd860-a9fa-43d5-a4f2-8c58e83a3d83)

# Suggestion
It would be nice to provide a short but concise description in the project repository as this allows developers scanning through open-source projects to immediately see what the project is about without having to open it and read through the project's README.

**Comment by Mounayer** [comment]
You are absolutely right! I completely forgot about this. I have now updated the description for the project repository and also provided tags! Thank you for catching this!
