### ISSUE TITLE
Nitpick: No mention of dependencies or packages used

### ISSUE THREAD

**Issue by cleobnvntra** [Mounayer/OptimizeIt#6]
# Description
README contains detailed instructions on how to use the tool and the various command options it supports. However, the README does not provide any information about the tool's dependencies or packages used.

# Suggestion
- Adding a section for dependencies/packages used for the tool where it explains what the package is and what its use is in the tool.
- Provide a link to their docs for ease of access for more details about the said dependency or package.
- Provide the command necessary to install the dependency.

Having this information allows the developer reading through the project to immediately know the packages used in the tool without having to look through the packages installed in package.json.

This also allows the developer to easily know the commands needed to install any dependencies or packages individually in the event that something goes wrong when installing the dependencies through package.json.

**Comment by Mounayer** [comment]
You are correct, I updated the README.md to include a list of notable dependencies used in the project, this was updated in PR #9
