### ISSUE TITLE
BUG: groqClient baseURL is broken

### ISSUE THREAD

**Issue by cleobnvntra** [Mounayer/OptimizeIt#8]
# Description
Using the provided baseURL by openai (`https://api.openai.com/v1`) seems to be not working. It might be a GROQ client or openai issue as it seems to be returning a 404 status from the request made when running the tool with this baseURL.

```
private constructor(apiKey: string) {
    this.groqClient = new Groq({
      apiKey,
      baseURL: 'https://api.openai.com/v1',
    });
  }
```

Running the tool with this baseURL produces an error:

```
Error Message: Unknown request URL: POST /v1/openai/v1/chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/., Error Type: invalid_request_error
```

# Temporary fix
I was able to run the tool properly by either removing the baseURL completely or by using `https://api.groq.com` which I retrieved from GROQ's [docs](https://console.groq.com/docs/openai).

NOTE: The docs provide `https://api.groq.com/openai/v1` as the baseURL which also does not work.

Based on my observation, in the error produced it seems that the POST request is adding an additional `/v1/chat/completions` in the request url. So i figured removing `/openai/v1` and it seems to have worked for this specific baseURL.

**Comment by Mounayer** [comment]
This is very weird. I tested it the other day and it worked without any problem. I think it's broken on their side too. I have removed the `baseUrl` completely from the `Groq` client and it now works properly. This was updated in PR #9 -- Thanks for catching this!
